---
# vim: set ft=yaml:

- name: Deploy Strimzi
  delegate_to: localhost
  kubernetes.core.helm:
    name: strimzi
    chart_ref: "{{ q('pipe', 'git rev-parse --show-toplevel')[0] }}/charts/strimzi-kafka-operator/helm-charts/helm3/strimzi-kafka-operator"
    # chart_version: 0.8.2
    wait: true
    release_namespace: default
    values: "{{ lookup('ansible.builtin.template', 'strimzi-values.yaml.j2') | from_yaml }}"

- name: Deploy Kafka
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
  with_fileglob:
    - "../templates/kafka-*.j2"

- name: Wait for Kafka to be deployed
  delegate_to: localhost
  shell: kubectl wait kafka theodolite-kafka --for=condition=Ready --timeout=600s
