---
# vim: set ft=yaml:

- name: Deploy Theodolite
  delegate_to: localhost
  kubernetes.core.helm:
    name: theodolite
    chart_ref: "{{ q('pipe', 'git rev-parse --show-toplevel')[0] }}/charts/theodolite/helm"
    # chart_version: 0.8.2
    wait: true
    release_namespace: default
    values: "{{ lookup('ansible.builtin.template', 'theodolite-values.yaml.j2') | from_yaml }}"
# - name: Wait for Theodolite's Kafka to be deployed
#   delegate_to: localhost
#   shell: kubectl wait kafka theodolite-kafka --for=condition=Ready --timeout=600s

- name: Patch benchmarks
  delegate_to: localhost
  ansible.builtin.command:
    cmd: >-
      kubectl patch benchmarks {{ item }} --type json
      --patch "[{op: replace, path: /spec/loadTypes/0/patchers/1/properties/loadGenMaxRecords, value: {{ MAX_RECORDS_PER_INSTANCE }} }]"
  with_items: "{{ benchmarks }}"
  register: patch_result
  failed_when: "'error' in patch_result.stderr"
